# Neural Networks and Deep Learning

This notebook is based on my learning from **course 1** of the **Deep Learning Specialization** provided by **deeplearning.ai**. The course videos could be found on [YouTube](https://www.youtube.com/watch?v=CS4cs9xVecg&list=PLkDaE6sCZn6Ec-XTbcX1uRg2_u4xOEky0) or [Coursera](https://www.coursera.org/specializations/deep-learning). Learning through Coursera is highly recommended to get access to the quizes and programmin exercises along the course, as well as the course certification upon completion. Personally, I completed the specialization of 5 coursesand acquired [Specialization Certificate](https://coursera.org/share/e590c28a5c258e500ca6d3ccb4ed57ba). Later, I discovered the YouTube videos and used them for review.

## 1. Introduction to deep learning

A neuron is a function, such as sigmoid or ReLu, that transforms an input into an output. We can built a very simple model with just one neural. Neurons in **hidden layer** can also be viewed as the **(hidden) features** which human consider when making decisions.

Although the success of deep learning applications has been focused on unstructured data, such as image classification, there is still a lot of short-term economic value that applying deep learning creates has been on structured data, such as online advertising or big amount of data that company owns. Therefore, when thinking about deep learning in real case, don't forget to also consider possibilities of applying it on structured data.

Scales (both the size of NN and amount of labeled data) derives deep learning progress.

## 2. Neural Networks Basics

### Notation of binary classfication
$\mathbf{x} \in \mathbf{R}^{n_x}, y \in {0, 1}$

m training samples: ${(x^{(1)}, y^{(1)}), (x^{(2)}, y^{(2)}), ..., (x^{(m)}, y^{(m)})}$

$m = m_{train}, m_{test} =$ # of test samples

$\mathbf{X} = \begin{bmatrix}
| & | &  & | \\
x^{(1)} & x^{(2)} & \cdots & x^{(m)} \\
| & | &  & | \\ 
\end{bmatrix}$

$\mathbf{X} \in \mathbf{R^{n_x*m}}$ X-shape = $(n_x, m)$

#### Note: The vectors of x are stacked horizontally instead of vertically, which is usually used in other classficiation models. The same applies to y as below.

$\mathbf{Y} = [y^{(1)}, y^{(2)}, ..., y^{(m)}]$

$\mathbf{Y} \in \mathbf{R}^{1*m}$, Y-shape = $(1,m)$


### Logistic Regression
Given $x$, want $\hat{y} = P(y=1|x)$

$x \in \mathbf{R}^{n_x}$

Parameters: $w \in \mathbf{R}^{n_x}, b \in \mathbf{R}$

Output: $\hat{y} = \sigma(w^tx + b)$ 

Sigmoid function is applied to the output of linear regression. $\sigma(z) = \frac{1}{1+e^{-z}}$

- If $z$ is large then $\sigma(z) \approx \frac{1}{1+0}=1$

- If $z$ is large negative then $\sigma(z) \approx \frac{1}{1+Bignum}=0$

### Logistic Regression Lost Function
$L(\hat{y}, y) = -(y*log\hat{y}+(1-y)*log(1-\hat{y}))$

- If $y=1, L(\hat{y},y)=-log\hat{y} \leftarrow$ want $log\hat{y}$ to be large, want $\hat{y}$ to be large

- If $y=0, L(\hat{y},y)=-log(1-\hat{y}) \leftarrow$ want $log(1-\hat{y})$ to be large, want $\hat{y}$ to be small

Cost function: $J(w, b) = \frac{1}{m}\sum_{i=1}^{m}L(\hat{y}^{(i)}, y^{(i)}) = -\frac{1}{m}\sum_{i=1}^{m}[y^{(i)}log\hat{y}^{(i)}+(1-y^{(i)})log(1-\hat{y}^{(i)})]$

Want to find $w,b$ that minimize $J(w,b)$. $J(w,b)$ is a **convext function**, and this is the big reason why we use this cost function.

#### [Important Concept] Logistic regression can be viewed as a small nueral network.

### Gradient Descent
Repeat {

Compute predicts $\hat{y}$ and cost function $J(w, b) = \frac{1}{m}\sum_{i=1}^{m}L(\hat{y}, y)$

$w:=w-\alpha\frac{\partial J(w, b)}{\partial w}$ 

$b:=b-\alpha\frac{\partial J(w, b)}{\partial b}$ 

}

$\partial$ means partial derivative when there are two variables.

$\alpha$ is the learning rate and $\frac{\partial J(w, b)}{\partial w}$ is the update of $w$. The derivative of the function is the slope of the function at the point. 

A convention of $\frac{\partial J(w, b)}{\partial w}$ in later courses will be $dw$, and $\frac{\partial J(w, b)}{\partial b}$ will be $db$.

#### Backpropagation is the process of getting derivatives and update paramaters

### Logistic regression derivatives (C1W2L09)

**Computational Graph - Forwardpropagation**

$\fbox{$x_1, ..., x_n, w_1, ..., w_n$}\rightarrow$ $\fbox{$z = w_1x_1 + w_2x_2 + ... + w_nx_n + b = w^Tx + b$}\rightarrow$ $\fbox{$a = \sigma(z)$}\rightarrow $$\fbox{$L(a,y)=-(ylog(a)+(1-y)log(1-a))$}$ 


**Computational Graph - Backpropagation**

#### [VERY IMPORTANT NOTE!!!]: In backpropagation, what we want to do is to - get the derivative of $z, w, \text{and } b$ repective to  LOST $L(a,y)$ *so that we can gradually minimize the cost of lost function*. We need $da$ to compute $dz$.

$\fbox{$x_1, ..., x_n, w_1, ..., w_n$}$ <font color='green'>$\Leftarrow$</font>  $\fbox{$z = w_1x_1 + w_2x_2 + ... + w_nx_n + b = w^Tx + b$}$ <font color='blue'>$\Leftarrow$</font> $\fbox{$a = \sigma(z)$}$ <font color='brown'>$\Leftarrow $</font> $\fbox{$L(a,y)=-(ylog(a)+(1-y)log(1-a))$}$ 

<font color='brown'>$$da = \frac{dL(a,y)}{da} = -\frac{y}{a} + \frac{1-y}{1-a}$$</font>

<font color='blue'>$$dz = \frac{dL}{dz} = \frac{dL(a,y)}{dz} = \frac{dL}{da}\frac{da}{dz} = da \times g'(z) = (-\frac{y}{a} + \frac{1-y}{1-a}) (a(1-a)) = a-y \text{ (Chain Rule)}$$</font>

<font color='green'>$$dw = \frac{\partial L}{\partial w_n} =\frac{dL}{da}\frac{da}{dz}\frac{\partial z}{\partial dw} = x_ndz$$</font>
<font color='green'>$$db = \frac{\partial L}{\partial b} = dz$$</font>

### Vectorization for m samples & Recap

#### Forwardpropagation

$\mathbf{X} = \begin{bmatrix}
| & | &  & | \\
x^{(1)} & x^{(2)} & \cdots & x^{(m)} \\
| & | &  & | \\ 
\end{bmatrix}, \mathbf{w} = \begin{bmatrix}
w_1 \\
w_2 \\
\vdots \\
w_n\\ 
\end{bmatrix}$

$$\mathbf{Z} = [z^{(1)}, z^{(2)}, ..., z^{(m)}] = \mathbf{w}^T\mathbf{X}+\mathbf{b}
$$

$$\mathbf{A} = \sigma(\mathbf{Z})$$

#### Backpropagation (C1W2L14)

**For n samples:**

$dz^{(1)} = a^{(1)} - y^{(1)}, dz^{(2)} = a^{(2)} - y^{(2)}, ...$

$\mathbf{dZ} = [dz^{(1)}, dz^{(2)}, ..., dz^{(m)}]$

$\mathbf{A} = [a^{(1)} ... a^{(m)}], \mathbf{Y} = [y^{(1)} ... y^{(m)}]$

$$\mathbf{dZ} = A-Y$$

$$db = \frac{1}{m}\sum_{i=1}^{m}dz^{(i)} = \frac{1}{m}np.sum(\mathbf{dZ})$$

$$\mathbf{dw} = \frac{1}{m}\mathbf{X}\mathbf{dZ}^T$$

$$\mathbf{w}:=\mathbf{w}-\alpha \mathbf{dw}$$
$$b:=w-\alpha db$$

### Relevant codes in Numpy

In [3]:
import numpy as np

In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# vectorization
c = np.dot(a,b)
print(c)

250204.84932320815


In [6]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [8]:
# broadcasting
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
# rank 1 array - doesn't behave like a vector
print(np.random.randn(5).shape)
# column vector
print(np.random.randn(5,1).shape)

(5,)
(5, 1)


## 3. 2-Layer Neural Network

Recall in **logistic regression**:

$$z = w^Tx + b \rightarrow a=\sigma(z) \rightarrow L(a,y)$$

In **neural network**, there are more layers, in which there are neurons similar to a logistic regression. The parameters correspond to the first layer of neuron will be denoted with superscript $[1]$, and so on.

$$z^{[1]} = w^{[1]}x+b^{[1]} \rightarrow a^{[1]}=g^{[1]}(z^{[1]}) \rightarrow z^{[2]} = w^{[2]}a^{[1]}+b^{[2]} \rightarrow a^{[2]}=g^{[2]}(z^{[2]}) \rightarrow L(a^{[2]}, y)$$

$g^{[i]}$ is the activation function of layer $i$.

### Representation
- Input layer
    - $a^{[0]}=x$
- Hidden layer
    - $a^{[1]} = \begin{bmatrix}
                {a_1}^{[1]} \\
                {a_2}^{[1]} \\
                \vdots \\
                {a_n}^{[1]}\\ 
                \end{bmatrix}$
- Output layer

When we count the layers we don't don't the input layer. A NN with only 1 hidden layer is called 2 layer NN.

### Forwardpropagation

Given input $\mathbf{X} = \begin{bmatrix}
| & | &  & | \\
x^{(1)} & x^{(2)} & \cdots & x^{(m)} \\
| & | &  & | \\ 
\end{bmatrix}$:                                               

$$\mathbf{Z}^{[1]} = \mathbf{w}^{[1]}\mathbf{X} + \mathbf{b}^{[1]}$$

$$\mathbf{A}^{[1]} = g^{[1]}(\mathbf{Z}^{[1]})$$

$$\mathbf{Z}^{[2]} = \mathbf{w}^{[2]}\mathbf{A}^{[1]} + \mathbf{b}^{[2]}$$
                                
$$\mathbf{A}^{[2]} = g^{[2]}(\mathbf{Z}^{[2]})$$


, where $\mathbf{w}^{[1]} = \begin{bmatrix}
                            - {w_1}^{[1]T}- \\
                            - {w_2}^{[1]T}- \\
                            \vdots \\
                            - {w_i}^{[1]T}-\\ 
                            \end{bmatrix},
          \mathbf{b}^{[1]} = \begin{bmatrix}
                            {b_1}^{[1]T}\\
                            {b_2}^{[1]T}\\
                            \vdots \\
                            {b_i}^{[1]T}\\ 
                            \end{bmatrix},
          \mathbf{Z}^{[1]} = \begin{bmatrix}
                       | & | &  & | \\
                       z^{[1](1)} & z^{[1](2)} & \cdots & z^{[1](m)} \\
                       | & | &  & | \\ 
                       \end{bmatrix},
          \mathbf{A}^{[1]} = \begin{bmatrix}
                       | & | &  & | \\
                       a^{[1](1)} & a^{[1](2)} & \cdots & a^{[1](m)} \\
                       | & | &  & | \\ 
                       \end{bmatrix}$

The shape of $\mathbf{w}^{[1]}$ is $(n^{[1]}, n^{[0]})$, and the shape of $\mathbf{b}^{[1]}$ is $(n^{[1]}, 1)$, where $n^{[1]} =$ the number of neurons in first layer and $^{[0]} =$ dimensions of $x$.

The shape of $\mathbf{Z}^{[1]}$ and $\mathbf{A}^{[1]}$ is $(n^{[1]}, m)$.

#### Note: $(n^{[1]}, n^{[0]}) \times (n^{[0]}, m) = (n^{[1]}, m)$


### Gradient Descent

Parameters: $\mathbf{w}^{[1]}, \mathbf{b}^{[1]}, \mathbf{w}^{[2]}, \mathbf{b}^{[2]}$

Cost function: $J(\mathbf{w}^{[1]}, \mathbf{b}^{[1]}, \mathbf{w}^{[2]}, \mathbf{b}^{[2]}) = \frac{1}{m}\sum_{i=1}^{n}L(\hat{y},y)$

#### Note: The relationship between $\mathbf{w}^{[1]}, \mathbf{b}^{[1]}, \mathbf{w}^{[2]}, \text{and } \mathbf{b}^{[2]}$ is non-linear, so don't conceptualize it in a linear way. Therefore, the derivatives are all respective to the cost function $J$ as below. During the iteration, we really only want to update $\mathbf{w}^{[1]}, \mathbf{b}^{[1]}, \mathbf{w}^{[2]}, \text{and } \mathbf{b}^{[2]}$ but inevitably need to calculate $\mathbf{dZ}$ to achieve the goal (see formula).

Repeat in one iteration {

Compute predicts $\mathbf{\hat{y}}$

$\mathbf{dw}^{[1]} = \frac{\partial J}{\partial \mathbf{w}^{[1]}}, \mathbf{db}^{[1]} = \frac{\partial J}{\partial \mathbf{b}^{[1]}}, \mathbf{dw}^{[2]} = \frac{\partial J}{\partial \mathbf{w}^{[2]}}, \mathbf{db}^{[2]} = \frac{\partial J}{\partial \mathbf{b}^{[2]}}$

$\mathbf{w}^{[1]}:=\mathbf{w}^{[1]}-\alpha\mathbf{dw}^{[1]}, \mathbf{b}^{[1]}:=\mathbf{b}^{[1]}-\alpha\mathbf{db}^{[1]}, \mathbf{w}^{[2]}:=\mathbf{w}^{[2]}-\alpha\mathbf{dw}^{[2]}, \mathbf{b}^{[2]}:=\mathbf{b}^{[2]}-\alpha\mathbf{db}^{[2]}$ 

}

### Formula to Compute Derivatives - Backpropagation:
**Assuming $\sigma()$ is used in output layer.**

Refer to logistic regression for the following formula.
$$\mathbf{dZ}^{[2]} = A^{[2]}-Y$$
$$\mathbf{dw}^{[2]} = \frac{1}{m}\mathbf{dZ}^{[2]}\mathbf{A}^{[1]T}$$ 
$$db^{[2]} = \frac{1}{m}\sum_{i=1}^{m}dz^{[2]} = \frac{1}{m}np.sum(\mathbf{dZ}^{[2]}, axis=1, keepdims=True)$$

#### Note: The shape of $\mathbf{dZ}^{[1]}$ formula is $(n^{[1]}, m) \times (n^{[1]}, m)$.
$$\mathbf{dZ}^{[1]} = \mathbf{w}^{[2]T}\mathbf{dZ}^{[2]} \times g^{[1]'}(\mathbf{Z}^{[1]})$$
$$\mathbf{dw}^{[1]} = \frac{1}{m}\mathbf{dZ}^{[1]}\mathbf{X^T}$$
$$db^{[1]} = \frac{1}{m}\sum_{i=1}^{m}dz^{[1]} = \frac{1}{m}np.sum(\mathbf{dZ}^{[1]}, axis=1, keepdims=True)$$

How to get $\mathbf{dZ}^{[1]}$:
$$\mathbf{dZ}^{[1]} = \frac{\partial L}{\mathbf{\partial A}^{[1]}} \times \frac{\mathbf{dA}^{[1]}}{\mathbf{dZ}^{[1]}}= \frac{\partial L}{\mathbf{\partial A^{[1]}}} \times \frac{d}{dZ^{[1]}}g(\mathbf{Z}^{[1]}) = \mathbf{dA^{[1]}}\times g'(\mathbf{Z}^{[1]})$$

$$\mathbf{dA}^{[1]} = \frac{dL}{\mathbf{dZ}^{[2]}} \times \frac{\mathbf{dZ}^{[2]}}{\mathbf{dA}^{[1]}} = \mathbf{dZ}^{[2]} \frac{d(\mathbf{w}^{[2]}\mathbf{A}^{[1]}+\mathbf{b}^{[2]})}{\mathbf{dA}^{[1]}} = \mathbf{dZ}^{[2]}\mathbf{w}^{[2]}$$

#### More references:
- [Backpropagation calculas | Deep learning, chapter 3 by 3BLUE1BROWN](https://www.youtube.com/watch?v=Ilg3gGewQ5U) gives a clearer picture of backpropagation by visual representation
- [Backpropagation calculas | Deep learning, chapter 4 by 3BLUE1BROWN](https://www.youtube.com/watch?v=tIeHLnjs5U8) talks more about the ituition of chain rules


### Activation Functions

Sigmoid function is one of the activation functions. A better activation function is **tanh function**, which is a mathmatically shifted function of sigmoid function. The tanh function goes through 0 and scales between -1 and +1. $$tanh(z) = \frac{e^z-e^{-z}}{e^z+e^{-z}}$$

For hidden units, if you let the actifunction $g(z)$ be equal to $tanh(z)$, this almost always works better than sigmoid function. With values between -1 and +1, the means of the activations that come out of the hidden layer are closer to have a zero mean just as sometimes we center our data when we train the model. This makes the learning of the next layer a bit eaiser. One situation to keep using sigmoid function is at the output layer for classification. However, one disadvantage of tanh function is the gradient becomes very small when z is very large or very small.

One other choise that is popular for machine learning is **ReLu (rectified linear unit) function**
$$a = max(0, z)$$

One disadvantage of ReLu is that the derivative is 0 then z is negative. In practice, it works just fine as most of the hidden units will deliver z > 0. We can use leaky ReLu solves this issue, but it is less common.

### Pros and Cons

- **Sigmoid**: Never use this unless for the output layer. 
- **Tanh**: A better option than sigmoid
- **ReLu**: Most commonly used
- **Leaky Relu**: An alternative of ReLu

If not sure which activation function works the best, try them all and use validation set to see which one works better.

### Derivatives of Activation Functions

**Sigmoid: $g(z) = \frac{1}{1+e^{-z}}$** 

$$\frac{d}{dz}g(z) = \text{slope of $g(x)$ at } z = g'(z) =\frac{1}{1+e^{-z}}(1-\frac{1}{1+e^{-z}}) = g(z)(1-g(z)) = a(1-a)$$

**tanh: $g(z) = \frac{e^z-e^{-z}}{e^z+e^{-z}}$**

$$\frac{d}{dz}g(z)=1-(tanh(z))^2 = 1-a^2$$

**ReLU: $g(z) = max(0, z)$**

$$\begin{equation}
  g'(z)=\begin{cases}
    0, & \text{if $z<0$}\\
    1, & \text{if $z\geq0$}
  \end{cases}
\end{equation}
$$

**Leaky ReLU: $g(z) = max(0.01z, z)$**

$$\begin{equation}
  g'(z)=\begin{cases}
    0.01, & \text{if $z<0$}\\
    1, & \text{if $z\geq0$}
  \end{cases}
\end{equation}
$$


## 4. Deep Neural Networks

### Notation
- $L =$ number of layers
- $n^{[l]} =$ number of units in layer $l$
- $a^{[l]} =$ activations in layer $l$
- $a^{[l]} = g^{[l]}(z^{[l]})$
- $w^{[l]}, b^{[l]} =$ the weight and bias in layer $l$
- $x = a^{[0]}, \hat{y} = a^{[L]}$

### Forwardpropagation

for $l$ from 1 to $l$:

$\mathbf{Z}^{[l]} = \mathbf{w}^{[l]}\mathbf{A}^{[l-1]} + \mathbf{b}^{[l]}$ The shape of $w^{[l]} \text{ and } b^{[l]} : (n^{[l]}, n^{[l-1]})$ as we need to transform the dimensions from $n^{[l-1]}$ to $n^{[l]}$                     
$\mathbf{A}^{[l]} = g^{[l]}(\mathbf{Z}^{[l]})$ The shape of $\mathbf{Z}^{[l]} \text{ and } \mathbf{A}^{[l]} : (n^{[l]}, m)$

The for loop here is inevitable.

### Why Deep Representations?

1. First few layers are simpler functions that learns lower-level features, and then the outputs are feeded into later layers of more complex functions to detect more complex things.

2. Circuit theory and deep learning (informally): There are functions you can compute with a "small" L-layer deep neural network that shaoower networks require exponentially more hidden units to compute. Ex: from $O(log n)$ to $O(2^n)$

3. Neural network rebranded as deep learning

When starting a new questions, start with simple NN models.

### Forward and backward functions

large $l$: $w^{[l]}, b^{[l]}$

Forward: 
- Input $A^{[l-1]}$; 
- Output $A^{[l]}$, cache $Z^{[l]}$

Backward: 
- Input $dA^{[l]}$, cached $Z^{[l]}$; 
- Output: $dA^{[l-1]}, dw^{[l]}, db^{[l]}$

### Back Propagation

$\mathbf{dZ}^{[l]} = \mathbf{dA}^{[l]} \times g^{[l]'}(\mathbf{Z})^{[l]}$

$\mathbf{dw}^{[l]} = \frac{1}{m}\mathbf{dZ}^{[l]} \mathbf{A}^{[l-1]}$

$\mathbf{db}^{[l]} = \frac{1}{m}np.sum(\mathbf{dZ}^{[l]}, asix=1, keepdims=True)$

$\mathbf{dA}^{[l-1]} = \mathbf{w}^{[l]T} \mathbf{dZ}^{[l]}$

The output layer: $da^{[l]} = -\frac{y}{a} + \frac{1-y}{1-a}$

### Gradient Descent

$\mathbf{w}^{[l]}:=\mathbf{w}^{[l]}-\alpha\mathbf{dw}^{[l]}$ 

$\mathbf{b}^{[l]}:=\mathbf{b}^{[l]}-\alpha\mathbf{db}^{[l]}$ 

### Parameters and Hyperparameters

Parameters: $\mathbf{w}, \mathbf{b}$

Hyperparameters: the parameters (used/experimented during training) that control $\mathbf{w}, \mathbf{b}$
- learning rate $\alpha$
- number of iteration
- number of hidden layer $L$
- number of hidden units $n^{[l]}$
- choice of activation functions
- momentum
- minibatch size
- regularization
- and more

Hyperparameters determins the final parameters we end up with.

Try out a range of hyperparameters when starting a new problem and then tune the hyperparameters in a systematic way. Overtime, the best hyperparameters might change for the same problem.