# Neural Networks and Deep Learning

This notebook is based on my learning from course 1 of the **Deep Learning Specialization** provided by **deeplearning.ai**. The course videos could be found on [YouTube](https://www.youtube.com/watch?v=CS4cs9xVecg&list=PLkDaE6sCZn6Ec-XTbcX1uRg2_u4xOEky0) or [Coursera](https://www.coursera.org/specializations/deep-learning). Learning through Coursera is highly recommended to get access to the quizes and programmin exercises along the course, as well as the course certification upon completion. Personally, I completed the specialization of 5 coursesand acquired [Specialization Certificate](https://coursera.org/share/e590c28a5c258e500ca6d3ccb4ed57ba). Later, I discovered the YouTube videos and used them for review.

## Introduction to deep learning

A neuron is a function, such as sigmoid or ReLu, that transforms an input into an output. We can built a very simple model with just one neural. Neurons in hidden layer can also be viewed as the (hidden) features which human consider when making decisions.

Although the success of deep learning applications has been focused on unstructured data, such as image classification, there is still a lot of short-term economic value that applying deep learning creates has been on structured data, such as online advertising or big amount of data that company owns. Therefore, when thinking about deep learning in real case, don't forget to also consider possibilities of applying it on structured data.

Scales (both the size of NN and amount of labeled data) derives deep learning progress.

## Neural Networks Basics

### Notation of binary classfication
$\mathbf{x} \in \mathbf{R}^{n_x}, y \in {0, 1}$

m training samples: ${(x^{(1)}, y^{(1)}), (x^{(2)}, y^{(2)}), ..., (x^{(m)}, y^{(m)})}$

$m = m_{train}, m_{test} =$ # of test samples

$\mathbf{X} = \begin{bmatrix}
| & | &  & | \\
x^{(1)} & x^{(2)} & \cdots & x^{(m)} \\
| & | &  & | \\ 
\end{bmatrix}$

$\mathbf{X} \in \mathbf{R^{n_x*m}}$ X-shape = $(n_x, m)$

#### Note: The vectors of x are stacked horizontally instead of vertically, which is usually used in other classficiation models. The same applies to y as below.

$\mathbf{Y} = [y^{(1)}, y^{(1)}, ..., y^{(1)}]$

$\mathbf{Y} \in \mathbf{R}^{1*m}$, Y-shape = $(1,m)$


### Logistic Regression
Given $x$, want $\hat{y} = P(y=1|x)$

$x \in \mathbf{R}^{n_x}$

Parameters: $w \in \mathbf{R}^{n_x}, b \in \mathbf{R}$

Output: $\hat{y} = \sigma(w^tx + b)$ 

Sigmoid function is applied to the output of linear regression. $\sigma(z) = \frac{1}{1+e^{-z}}$

- If $z$ is large then $\sigma(z) \approx \frac{1}{1+0}=1$

- If $z$ is large negative then $\sigma(z) \approx \frac{1}{1+Bignum}=0$

### Logistic Regression Lost Function
$L(\hat{y}, y) = -(y*log\hat{y}+(1-y)*log(1-\hat{y}))$

- If $y=1, L(\hat{y},y)=-log\hat{y} \leftarrow$ want $log\hat{y}$ to be large, want $\hat{y}$ to be large

- If $y=0, L(\hat{y},y)=-log(1-\hat{y}) \leftarrow$ want $log(1-\hat{y})$ to be large, want $\hat{y}$ to be small

Cost function: $J(w, b) = \frac{1}{m}\sum_{i=1}^{m}L(\hat{y}^{(i)}, y^{(i)}) = -\frac{1}{m}\sum_{i=1}^{m}[y^{(i)}*log\hat{y}^{(i)}+(1-y^{(i)})*log(1-\hat{y}^{(i)})]$

Want to find $w,b$ that minimize $J(w,b)$. $J(w,b)$ is a **convext function**, and this is the big reason why we use this cost function.

#### [Important Concept] Logistic regression can be viewed as a small nueral network.

### Gradient Descent
Repeat {

$w:=w-\alpha\frac{\partial J(w, b)}{\partial w}$ 

$b:=b-\alpha\frac{\partial J(w, b)}{\partial b}$ 

}

$\partial$ means partial derivative when there are two variables.

$\alpha$ is the learning rate and $\frac{\partial J(w, b)}{\partial w}$ is the update of $w$. The derivative of the function is the slope of the function at the point. 

A convention of $\frac{\partial J(w, b)}{\partial w}$ in later courses will be $dw$, and $\frac{\partial J(w, b)}{\partial b}$ will be $db$.

#### Backpropagation is the process of getting derivatives and update paramaters

### Logistic regression derivatives (C1W2L09)

**For one sample:**

$z = w_1x_1 + w_2x_2 + ... + w_nx_n + b = w^Tx + b$ $\rightarrow$ $a = \sigma(z)$ $\rightarrow$ $L(a,y)$ 

$$\frac{dL(a,y)}{da} = -\frac{y}{a} + \frac{1-y}{1-a}$$

$$dz = \frac{dL}{dz} = \frac{dL(a,y)}{dz} = \frac{dL}{da}\frac{da}{dz} = (-\frac{y}{a} + \frac{1-y}{1-a}) (a(1-a)) = a-y$$

$$\frac{\partial L}{\partial w_n} = x_ndz, \frac{\partial L}{\partial b} = dz$$

### Vectorization for m samples & Recap

#### Forwardpropagation

$\mathbf{X} = \begin{bmatrix}
| & | &  & | \\
x^{(1)} & x^{(2)} & \cdots & x^{(m)} \\
| & | &  & | \\ 
\end{bmatrix}, \mathbf{w} = \begin{bmatrix}
w_1 \\
w_2 \\
\vdots \\
w_n\\ 
\end{bmatrix}$

$$\mathbf{Z} = [z^{(1)}, z^{(2)}, ..., z^{(m)}] = \mathbf{w}^T\mathbf{X}+\mathbf{b}
$$

$$\mathbf{A} = \sigma(\mathbf{Z})$$

#### Backpropagation (C1W2L14)

**For n samples:**

$dz^{(1)} = a^{(1)} - y^{(1)}, dz^{(2)} = a^{(2)} - y^{(2)}, ...$

$\mathbf{dZ} = [dz^{(1)}, dz^{(2)}, ..., dz^{(m)}]$

$\mathbf{A} = [a^{(1)} ... a^{(m)}], \mathbf{Y} = [y^{(1)} ... y^{(m)}]$

$$\mathbf{dZ} = A-Y$$

$$db = \frac{1}{m}\sum_{i=1}^{m}dz^{(i)} = \frac{1}{m}np.sum(\mathbf{dZ})$$

$$\mathbf{dw} = \frac{1}{m}\mathbf{X}\mathbf{dZ}^T$$

$$\mathbf{w}:=\mathbf{w}-\alpha \mathbf{dw}$$
$$b:=w-\alpha db$$

### Relevant codes in Numpy

In [3]:
import numpy as np

In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# vectorization
c = np.dot(a,b)
print(c)

250204.84932320815


In [6]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [8]:
# broadcasting
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
# rank 1 array - doesn't behave like a vector
print(np.random.randn(5).shape)
# column vector
print(np.random.randn(5,1).shape)

(5,)
(5, 1)


## Shallow Neural Network

Recall in **logistic regression**:

$$z = w^Tx + b \rightarrow a=\sigma(z) \rightarrow L(a,y)$$

In **neural network**, there are more layers, in which there are neurons similar to a logistic regression. The parameters correspond to the first layer of neuron will be denoted with superscript $[1]$, and so on.

$$z^{[1]} = w^{[1]}x+b^{[1]} \rightarrow a^{[1]}=\sigma(z^{[1]}) \rightarrow z^{[2]} = w^{[2]}a^{[1]}+b^{[2]} \rightarrow a^{[2]}=\sigma(z^{[2]}) \rightarrow L(a^{[2]}, y)$$

### Neural Network Representation
- Input layer
    - $a^{[0]}=x$
- Hidden layer
    - $a^{[1]} = \begin{bmatrix}
                {a_1}^{[1]} \\
                {a_2}^{[1]} \\
                \vdots \\
                {a_i}^{[1]}\\ 
                \end{bmatrix}$
- Output layer

When we count the layers we don't don't the input layer. A NN with only 1 hidden layer is called 2 layer NN.

**2 layer NN:**

Given input $\mathbf{X} = \begin{bmatrix}
| & | &  & | \\
x^{(1)} & x^{(2)} & \cdots & x^{(m)} \\
| & | &  & | \\ 
\end{bmatrix}$:                                               

$$\mathbf{Z^{[1]}} = \mathbf{w^{[1]}}\mathbf{X} + \mathbf{b^{[1]}}$$

$$\mathbf{A^{[1]}} = \sigma(\mathbf{Z^{[1]}})$$

$$\mathbf{Z^{[2]}} = \mathbf{w^{[2]}}\mathbf{A^{[1]}} + \mathbf{b^{[2]}}$$
                                
$$\mathbf{A^{[2]}} = \sigma(\mathbf{Z^{[2]}})$$


, where $\mathbf{w^{[1]}} = \begin{bmatrix}
                            - {w_1}^{[1]T}- \\
                            - {w_2}^{[1]T}- \\
                            \vdots \\
                            - {w_i}^{[1]T}-\\ 
                            \end{bmatrix},
          \mathbf{b^{[1]}} = \begin{bmatrix}
                            {b_1}^{[1]T}\\
                            {b_2}^{[1]T}\\
                            \vdots \\
                            {b_i}^{[1]T}\\ 
                            \end{bmatrix},
          \mathbf{Z^{[1]}} = \begin{bmatrix}
                       | & | &  & | \\
                       z^{[1](1)} & z^{[1](2)} & \cdots & z^{[1](m)} \\
                       | & | &  & | \\ 
                       \end{bmatrix},
          \mathbf{A^{[1]}} = \begin{bmatrix}
                       | & | &  & | \\
                       a^{[1](1)} & a^{[1](2)} & \cdots & a^{[1](m)} \\
                       | & | &  & | \\ 
                       \end{bmatrix}$

The shape of $\mathbf{w^{[1]}}$ is $(i, n)$, and the shape of $\mathbf{b^{[1]}}$ is $(i, 1)$, where $i =$ the number of neurons in first layer and $n =$ dimensions of $x$.

The shape of $\mathbf{Z^{[1]}}$ and $\mathbf{A^{[1]}}$ is $(i, m)$.

#### Note: $(i, n) \times (n, m) = (i, m)$

### Activation Functions

Sigmoid function one of the activation functions. A better activation function is **tanh function**, which is a mathmatically shifted function of sigmoid function. The tanh function goes through 0 and scales between -1 and +1. $$tanh(z) = \frac{e^z-e^{-z}}{e^z+e^{-z}}$$

For hidden units, if you let the actifunction $g(z)$ be equal to $tanh(z)$, this almost always works better than sigmoid function. With values between -1 and +1, the means of the activations that come out of the hidden layer are closer to have a zero mean just as sometimes we center our data when we train the model. This makes the learning of the next layer a bit eaiser. One situation to keep using sigmoid function is at the output layer for classification. However, one disadvantage of tanh function is the gradient becomes very small when z is very large or very small.

One other choise that is popular for machine learning is **ReLu (rectified linear unit) function**
$$a = max(0, z)$$

One disadvantage of ReLu is that the derivative is 0 then z is negative. In practice, it works just fine as most of the hidden units will deliver z > 0. We can use leaky ReLu solves this issue, but it is less common.

### Pros and Cons

- **Sigmoid**: Never use this unless for the output layer. 
- **Tanh**: A better option than sigmoid
- **ReLu**: Most commonly used
- **Leaky Relu**: An alternative of ReLu

If not sure which activation function works the best, try them all and use validation set to see which one works better.

### Derivatives of Activation Functions

**Sigmoid: $g(z) = \frac{1}{1+e^{-z}}$** 

$$\frac{d}{dz}g(z) = \text{slope of $g(x)$ at } z = g'(z) =\frac{1}{1+e^{-z}}(1-\frac{1}{1+e^{-z}}) = g(z)(1-g(z)) = a(1-a)$$

**tanh: $g(z) = \frac{e^z-e^{-z}}{e^z+e^{-z}}$**

$$\frac{d}{dz}g(z)=1-(tanh(z))^2 = 1-a^2$$

**ReLU: $g(z) = max(0, z)$**

$$\begin{equation}
  g'(z)=\begin{cases}
    0, & \text{if $z<0$}\\
    1, & \text{if $z\geq0$}
  \end{cases}
\end{equation}
$$

**Leaky ReLU: $g(z) = max(0.01z, z)$**

$$\begin{equation}
  g'(z)=\begin{cases}
    0.01, & \text{if $z<0$}\\
    1, & \text{if $z\geq0$}
  \end{cases}
\end{equation}
$$

## Deep Neural Networks